services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - node_modules_backend:/app/node_modules/
    environment:
      - JWT_SECRET
      - JWT_TOKEN_EXPIRATION
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules/
    restart: on-failure
  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres

  # adminer:
  #   image: adminer
  #   ports:
  #     - "8080:8080"
volumes:
  node_modules_backend:
  node_modules_frontend:
